/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "agia-triada": {
    "base": "agia-triada",
    "width": 1920,
    "height": 2560,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "ancient-aptera": {
    "base": "ancient-aptera",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "beach": {
    "base": "beach",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 1920,
    "fallbackHeight": 1280,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "chania": {
    "base": "chania",
    "width": 1920,
    "height": 1279,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cretan-food": {
    "base": "cretan-food",
    "width": 906,
    "height": 800,
    "fallbackWidth": 800,
    "fallbackHeight": 706,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cretan-wine": {
    "base": "cretan-wine",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1540,
    "fallbackWidth": 1920,
    "fallbackHeight": 1540,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 1920,
    "height": 1003,
    "fallbackWidth": 800,
    "fallbackHeight": 418,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1920,
    "height": 1252,
    "fallbackWidth": 1920,
    "fallbackHeight": 1252,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "history": {
    "base": "history",
    "width": 1920,
    "height": 1238,
    "fallbackWidth": 800,
    "fallbackHeight": 516,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "lighthouse": {
    "base": "lighthouse",
    "width": 1920,
    "height": 1293,
    "fallbackWidth": 800,
    "fallbackHeight": 539,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "market": {
    "base": "market",
    "width": 1920,
    "height": 1440,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 1920,
    "height": 1080,
    "fallbackWidth": 1920,
    "fallbackHeight": 1080,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 1134,
    "height": 742,
    "fallbackWidth": 1134,
    "fallbackHeight": 742,
    "widths": [
      320,
      480,
      640,
      800,
      960
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "olive-grove": {
    "base": "olive-grove",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 1920,
    "height": 1272,
    "fallbackWidth": 800,
    "fallbackHeight": 530,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "venetian-harbour": {
    "base": "venetian-harbour",
    "width": 1920,
    "height": 868,
    "fallbackWidth": 800,
    "fallbackHeight": 362,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "village": {
    "base": "village",
    "width": 1920,
    "height": 1270,
    "fallbackWidth": 800,
    "fallbackHeight": 529,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "white-mountains": {
    "base": "white-mountains",
    "width": 1920,
    "height": 1280,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
